const PASSWORD_IS_REQUIRED = '密码是必填项'
const EMAIL_IS_REQUIRED = '邮箱是必填项'
const EMAIL_ALREADY_EXIST = '邮箱已被注册'
const EMAIL_DOSE_NOT_EXIST = '邮箱不存在'
const EMAIL_IS_INCORRECT = '邮箱格式错误'
const PASSORD_ERROR = '密码错误'
const UNAUTHORIZATION = '没有操作权限'
const UNPERMISSION = '请先登录'
const EMAIL_ERROR = '邮箱发送失败'
const CODE_IS_INCORRECT = '验证码错误'
const EXIST_CODE = '您在5分钟内已申请过验证码，请注意查收'

module.exports = {
  PASSWORD_IS_REQUIRED,
  EMAIL_IS_REQUIRED,
  EMAIL_ALREADY_EXIST,
  EMAIL_DOSE_NOT_EXIST,
  PASSORD_ERROR,
  UNAUTHORIZATION,
  UNPERMISSION,
  EMAIL_IS_INCORRECT,
  EMAIL_ERROR,
  CODE_IS_INCORRECT,
  EXIST_CODE,
}
